baseURL = "https://copy-cooper.github.io/"
copyright = "Copyright © 2023"
title = "Brandon Cooper"
#paginate = 10
enableRobotsTXT = true
googleAnalytics = "G-MJKF3MJYS5"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This settings allows inlining <script> and <style> tags in markdown,
      # which is useful and required to use Prism plugins, but may be dangerous
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  #quality = 75

[params]
  # dark or light, defaults to light
  defaultTheme = "dark"
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "green"
  # soft medium hard, defaults to medium
  themeContrast = "hard"
  author = "Brandon Cooper"
  subtitle = ""
  description = "Making an impact in today's hyper-connected world is tantamount to success. I help businesses thrive by taking a pragmatic approach to marketing based on data and analytics, then I share the results here for all to see!"

  [params.logo]
    text = "cooper"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]

  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 100 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 100

  # Social share links for posts:
  #   - iconSuite: "simple-icon" or "tabler-icon"
  #   - iconName: name of the icon from the "iconSuite"
  #   - {url} placeholder for post .Permalink
  #   - {title} placeholder for post .Title
  # See  https://github.com/bradvin/social-share-urls for more format strings
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "twitter"
    formatString = "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "linkedin"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "whatsapp"
    formatString = "whatsapp://send/?text={title}%20{url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "tumblr"
    formatString = "https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "pinterest"
    formatString = "http://pinterest.com/pin/create/button/?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "ycombinator"
    formatString = "https://news.ycombinator.com/submitlink?u={url}&t={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "vk"
    formatString = "http://vk.com/share.php?url={url}&title={title}&comment={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "xing"
    formatString = "https://www.xing.com/spi/shares/new?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "telegram"
    formatString = "https://telegram.me/share/url?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "tabler-icon"
    iconName = "mail"
    formatString = "mailto:?subject={title}&body={url}"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
#  [[menu.main]]
#    identifier = "projects"
#    name = "Projects"
#    url = "/projects"
#    weight = 20
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
#  [languages.de]
#    languageName = "Deutsch"
#    weight = 20
#    [languages.de.params.jsonResume]
#      present = "heute"
