#+HUGO_BASE_DIR: .
#+options: author:nil
#+startup: indent showall
* Blog
:PROPERTIES:
#+HUGO_SECTION: blog
#+HUGO_AUTO_SET_LASTMOD: t
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :robots index, nofollow
:END:
** Projects: EasyTrim Reveals, QuickPanel, & FastPlank
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: case-study-easytrim
:EXPORT_FILE_NAME: index
:END:
#+hugo: {{< video src="case-study-easytrim" autoplay="true" controls="true" loop="true" >}}

Client: Engage Building Products

Services: Content Writing, SEO, UX

Completion Date: 2021-10-01

#+hugo: more

As the largest supplier of ACM panels in North America, Engage has a strong customer base who appreciate the proprietary technologies that make their products truly stand out from the crowd. Wanting to emphasize the key differentiators that make their products superior, I worked with Engage personally to help fulfill their vision for their brand.

Before content creation started, attention was paid to defining the client's audience. By looking at their user's needs, we were able to discover what made each type of customer special, helping us to better understand what they would need to know before making their first purchase.

We broke these user segments out into a few distinct groups: builders, homeowners, developers, architects, dealers, and installers. For each segment, we created lists of /need to know/ information specific to their needs. Those lists were then broken out into "quick fact" landing pages that could serve a few purposes. First, the homepage acted as a link-tree to help users quickly find the information they were looking for. Second, each page could be used for PPC ads as individual landing pages, ideal for segmenting audiences and ensuring users land on the best page for their demographic. Third, the pages provided a boost for SEO as they used specific language to rank for variant keywords in each niche.


This process was completed for each of the three major product categories for Engage Building Products—EasyTrim Reveals, QuickPanel, and FastPlank—all together ensuring that their business lines could rank well on Google for their own keywords while avoiding the keyword cannibalization that can occur when two pages on the same website contain overlapping information.

See these sites live at [[https://easytrimreveals.com/][easytrimreveals.com]], [[https://quickpanels.com/][quickpanels.com]], and [[https://fastplank.com/][fastplank.com]].

* Projects
